language: python
python:
  - "3.5"
cache: pip
install:
  - nvm install 6
  - npm install --only=dev
  - pip install -r requirements/dev.txt
script:
  - py.test --cov
  - ./node_modules/.bin/polylint -F
deploy:
 - provider: script
   script: scripts/deploy.sh
   on:
     branch: master
env:
  global:
    secure: YEspEcWPql1I0DSl7u+qdAzNEXLbVxgX5YcZkaisKalvhLP0QupBz565BExWl1qKSV5C9woXLikfMgMn7f+djiJ49wmIQN2mL9EQQgCdC8n8yN9MN2vhF46ZAm0JGjmN6E2nztK4/PElxe4I+SJqjTiUcv+mZ0VqQH3MrnjmLJG1WReaQv2KGQQpID9QWMyL2Mmd9XtrBxXB7VpGBbtBgB7AUmIUXu2KwXFtqmsy/PE9Em+cs5JPrNyGcOSDGw+1sK/TAIY6fOleRyAKhtZH3mLR0uq0Wcleibfjgi+2tIPijT4uZ3ksSo/FgiFpDPaFiQVPuhyxsAVutijxFSsyYsY1Q4ClwXw5uF8xmRS5WkMlWUjBxVcENKddOYg58Mvnvv25QGR7F0Jb7l3Qc+ZEeFd8OclWIOxt5erz5WZxTXDhSK1RtrfW+ri21XgEwWZYzDNmlhpV/kU02rCxkubR4PaToGkKr4Eb3VXaZVQrSiPlCX68x9tNRdgOKBTiP5RjJMjfjM0mGWew2VU1JfkwLQbd99ev/2irFbDRGRY73I8Zs1bq3akcmgH1VBsMdAtkrdYRGEvGUBjrlNAy27myKRbaZPI+ypRbAHAHmTSCwRsRHuG8aC0zun9h4zg/fZqAmshb0it/09E8a+YBp+16zkC+ECWR3PXXQW0k8eDY4VQ=
